{"name": "Log in fails with invalid credentials", "status": "passed", "start": 1713006332280, "stop": 1713006333936, "uuid": "880e556d-644f-4d71-bf95-cdac1690ff4a", "historyId": "8c58d11b652230ea7c05681c907c7513", "testCaseId": "8c58d11b652230ea7c05681c907c7513", "fullName": "tests.courier.test_login_courier.TestLoginCourier#test_login_fails_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WKST-QA-08"}, {"name": "thread", "value": "5028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_login_courier"}]}