{"name": "Log in fails with invalid credentials", "status": "passed", "start": 1713005968029, "stop": 1713005969647, "uuid": "c877b51c-bddf-430f-8929-c633c1072d9f", "historyId": "8c58d11b652230ea7c05681c907c7513", "testCaseId": "8c58d11b652230ea7c05681c907c7513", "fullName": "tests.courier.test_login_courier.TestLoginCourier#test_login_fails_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WKST-QA-08"}, {"name": "thread", "value": "26816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_login_courier"}]}