{"name": "Log in fails with invalid credentials", "status": "passed", "start": 1713006150418, "stop": 1713006152059, "uuid": "078efbf0-8a10-4e0f-ad8e-ac9c2d6b5e98", "historyId": "8c58d11b652230ea7c05681c907c7513", "testCaseId": "8c58d11b652230ea7c05681c907c7513", "fullName": "tests.courier.test_login_courier.TestLoginCourier#test_login_fails_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WKST-QA-08"}, {"name": "thread", "value": "20236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_login_courier"}]}